//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Randstad.UfoRsm.BabelFish.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Randstad.UfoRsm.BabelFish.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ClientId&quot;: &quot;0013L00000buT7kQAE&quot;,
        ///  &quot;ClientRef&quot;: &quot;CL-0279112&quot;,
        ///  &quot;ClientName&quot;: &quot;CPE New Client&quot;,
        ///  &quot;IsLegalHirer&quot;: false,
        ///  &quot;NoVat&quot;: false,
        ///  &quot;VatNo&quot;: null,
        ///  &quot;CompanyRegNum&quot;: null,
        ///  &quot;CreditLimit&quot;: null,
        ///  &quot;InvoiceDeliveryMethod&quot;: &quot;Billing Controlled&quot;,
        ///  &quot;InvoiceEmail&quot;: null,
        ///  &quot;InvoiceEmail2&quot;: null,
        ///  &quot;InvoiceEmail3&quot;: null,
        ///  &quot;EnablePaymentApplications&quot;: &quot;No&quot;,
        ///  &quot;IsCheckedIn&quot;: true,
        ///  &quot;WorkAddress&quot;: {
        ///    &quot;Street&quot;: &quot;Saint James&apos;s Building, 79 Oxford Street&quot;,
        ///    &quot;City&quot;: &quot;Manchester&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChildBillingControlled {
            get {
                return ResourceManager.GetString("ChildBillingControlled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ClientId&quot;: &quot;0013L00000ciwQhQAI&quot;,
        ///  &quot;ClientRef&quot;: &quot;CL-0279171&quot;,
        ///  &quot;ClientName&quot;: &quot;Sophie Direct Bill&quot;,
        ///  &quot;IsLegalHirer&quot;: false,
        ///  &quot;NoVat&quot;: false,
        ///  &quot;VatNo&quot;: null,
        ///  &quot;CompanyRegNum&quot;: null,
        ///  &quot;CreditLimit&quot;: 10000.0,
        ///  &quot;InvoiceDeliveryMethod&quot;: null,
        ///  &quot;InvoiceEmail&quot;: null,
        ///  &quot;InvoiceEmail2&quot;: null,
        ///  &quot;InvoiceEmail3&quot;: null,
        ///  &quot;EnablePaymentApplications&quot;: null,
        ///  &quot;IsCheckedIn&quot;: true,
        ///  &quot;WorkAddress&quot;: {
        ///    &quot;Street&quot;: &quot;120 High Street&quot;,
        ///    &quot;City&quot;: &quot;Luton&quot;,
        ///    &quot;County&quot;: null,
        ///    &quot;Country&quot;: nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChildElectronic {
            get {
                return ResourceManager.GetString("ChildElectronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ClientId&quot;: &quot;0013L00000buT7kQAE&quot;,
        ///  &quot;ClientRef&quot;: &quot;CL-0279112&quot;,
        ///  &quot;ClientName&quot;: &quot;CPE New Client&quot;,
        ///  &quot;IsLegalHirer&quot;: false,
        ///  &quot;NoVat&quot;: false,
        ///  &quot;VatNo&quot;: null,
        ///  &quot;CompanyRegNum&quot;: null,
        ///  &quot;CreditLimit&quot;: null,
        ///  &quot;InvoiceDeliveryMethod&quot;: &quot;Self Bill&quot;,
        ///  &quot;InvoiceEmail&quot;: null,
        ///  &quot;InvoiceEmail2&quot;: null,
        ///  &quot;InvoiceEmail3&quot;: null,
        ///  &quot;EnablePaymentApplications&quot;: &quot;Yes&quot;,
        ///  &quot;IsCheckedIn&quot;: true,
        ///  &quot;WorkAddress&quot;: {
        ///    &quot;Street&quot;: &quot;Saint James&apos;s Building, 79 Oxford Street&quot;,
        ///    &quot;City&quot;: &quot;Manchester&quot;,
        ///    &quot;Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChildSelfBill {
            get {
                return ResourceManager.GetString("ChildSelfBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;OpCo&quot;: {
        ///		&quot;Id&quot;: &quot;a3R3L000000Cl40UAC&quot;,
        ///		&quot;MigratedGroupId&quot;: &quot;CPE&quot;,
        ///		&quot;IsActive&quot;: null,
        ///		&quot;Name&quot;: &quot;CPE&quot;,
        ///		&quot;FinanceCode&quot;: &quot;CPE&quot;
        ///	},
        ///	&quot;AssignmentRef&quot;: &quot;PAs-821142&quot;,
        ///	&quot;PositionName&quot;: &quot;Administrator&quot;,
        ///	&quot;ExternalRef&quot;: null,
        ///	&quot;CheckIn&quot;: &quot;Checked In&quot;,
        ///	&quot;IR35&quot;: true,
        ///	&quot;PoNumber&quot;: null,
        ///	&quot;PoRequired&quot;: false,
        ///	&quot;StartDate&quot;: &quot;2023-09-01&quot;,
        ///	&quot;EndDate&quot;: &quot;2023-09-30&quot;,
        ///	&quot;AssignmentJobTitle&quot;: &quot;GDPR Temp gdpr test&quot;,
        ///	&quot;Owner&quot;: {
        ///		&quot;Id&quot;: &quot;0058d000002kbFbAAI&quot;,
        ///		&quot;MigratedUserId&quot;: null,
        ///		&quot;EmployeeRef&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_Assignment_Live {
            get {
                return ResourceManager.GetString("Debug_Assignment_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;LastModifiedDate&quot;: &quot;2022-01-13T09:24:15.000Z&quot;,
        ///  &quot;CreatedDate&quot;: &quot;2021-12-15T17:28:33.000Z&quot;,
        ///  &quot;WorkAddress&quot;: {
        ///    &quot;Street&quot;: &quot;68 Trinity Row&quot;,
        ///    &quot;PostCode&quot;: &quot;MK12 5PB&quot;,
        ///    &quot;County&quot;: &quot;Bucks&quot;,
        ///    &quot;Country&quot;: &quot;GB&quot;,
        ///    &quot;City&quot;: &quot;Milton Keynes&quot;
        ///  },
        ///  &quot;Unit&quot;: {
        ///    &quot;Name&quot;: &quot;Unit&quot;,
        ///    &quot;IsBilling&quot;: false,
        ///    &quot;Id&quot;: &quot;a3R8E000000EVm2UAG&quot;,
        ///    &quot;FinanceCode&quot;: &quot;B1325&quot;
        ///  },
        ///  &quot;StartDate&quot;: &quot;2021-12-16&quot;,
        ///  &quot;Region&quot;: {
        ///    &quot;Name&quot;: &quot;Region&quot;,
        ///    &quot;Id&quot;: &quot;a3R8E000000EVm0UAG&quot;
        ///  },
        ///  &quot;Rates&quot;: [
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_Assignment_Ltd {
            get {
                return ResourceManager.GetString("Debug_Assignment_Ltd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;LastModifiedDate&quot;: &quot;2022-02-03T08:50:52.000Z&quot;,
        ///    &quot;CreatedDate&quot;: &quot;2021-12-15T17:28:33.000Z&quot;,
        ///    &quot;WorkAddress&quot;: {
        ///        &quot;Street&quot;: &quot;68 Trinity Row&quot;,
        ///        &quot;PostCode&quot;: &quot;MK12 5PB&quot;,
        ///        &quot;County&quot;: &quot;Bucks&quot;,
        ///        &quot;Country&quot;: &quot;GB&quot;,
        ///        &quot;City&quot;: &quot;Milton Keynes&quot;
        ///    },
        ///    &quot;Unit&quot;: {
        ///        &quot;Name&quot;: &quot;Unit&quot;,
        ///        &quot;IsBilling&quot;: false,
        ///        &quot;Id&quot;: &quot;a3R8E000000EVm2UAG&quot;,
        ///        &quot;FinanceCode&quot;: &quot;B1325&quot;
        ///    },
        ///    &quot;StartDate&quot;: &quot;2021-12-16&quot;,
        ///    &quot;Region&quot;: {
        ///        &quot;Name&quot;: &quot;Region&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_Assignment_Paye {
            get {
                return ResourceManager.GetString("Debug_Assignment_Paye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;StartDate&quot;: &quot;2021-12-16&quot;,
        ///  &quot;SequenceNumber&quot;: &quot;0827236&quot;,
        ///  &quot;ReceiptRequired&quot;: false,
        ///  &quot;RateType&quot;: &quot;Basic Rate&quot;,
        ///  &quot;RateId&quot;: &quot;a0F8E00000pfqGhUAI&quot;,
        ///  &quot;PayUnit&quot;: &quot;Hourly&quot;,
        ///  &quot;PayRateCurrency&quot;: 10.00,
        ///  &quot;Margin&quot;: 33.33,
        ///  &quot;IsPayRise&quot;: false,
        ///  &quot;IsModifiedOnAssignment&quot;: true,
        ///  &quot;FeeRef&quot;: &quot;AF-827235&quot;,
        ///  &quot;EndDate&quot;: &quot;2021-12-17&quot;,
        ///  &quot;ChargeRateCurrency&quot;: 15.00,
        ///  &quot;Assignment&quot;: {
        ///    &quot;LastModifiedDate&quot;: &quot;2022-01-12T13:48:20.000Z&quot;,
        ///    &quot;CreatedDate&quot;: &quot;2021-12-15T17:28:33.000Z&quot;,
        ///    &quot;Unit&quot;: {
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_AssignmentRate {
            get {
                return ResourceManager.GetString("Debug_AssignmentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;FeeRef&quot;: &quot;AF-5667444&quot;,
        ///	&quot;FeeName&quot;: null,
        ///	&quot;StartDate&quot;: &quot;2023-08-01&quot;,
        ///	&quot;ExpenseType&quot;: null,
        ///	&quot;OvertimeType&quot;: null,
        ///	&quot;NonChargeableToClient&quot;: false,
        ///	&quot;PayUnit&quot;: &quot;Hourly&quot;,
        ///	&quot;SequenceNumber&quot;: &quot;5667445&quot;,
        ///	&quot;PayRateCurrency&quot;: 30.0,
        ///	&quot;ChargeRateCurrency&quot;: 50.0,
        ///	&quot;PostParityPayRateCurrency&quot;: null,
        ///	&quot;PostParityChargeRateCurrency&quot;: null,
        ///	&quot;RateType&quot;: &quot;Basic Rate&quot;,
        ///	&quot;Assignment&quot;: {
        ///		&quot;OpCo&quot;: {
        ///			&quot;Id&quot;: &quot;a3R4J000001MuDqUAK&quot;,
        ///			&quot;MigratedGroupId&quot;: null,
        ///			&quot;IsActive&quot;: null,
        ///			&quot;Name&quot;: &quot;Business Sol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_AssignmentRate_Live {
            get {
                return ResourceManager.GetString("Debug_AssignmentRate_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;CandidateId&quot;: &quot;a1C250000025lFoEAI&quot;,
        ///  &quot;LiveInPayroll&quot;: true,
        ///  &quot;CandidateRef&quot;: &quot;C-001677069&quot;,
        ///  &quot;Title&quot;: &quot;Mr&quot;,
        ///  &quot;Name&quot;: &quot;Gaid&quot;,
        ///  &quot;Surname&quot;: &quot;Yusuf&quot;,
        ///  &quot;Sex&quot;: &quot;Male&quot;,
        ///  &quot;DateOfBirth&quot;: &quot;2000-01-10T00:00:00&quot;,
        ///  &quot;NiNumber&quot;: &quot;SK198050C&quot;,
        ///  &quot;Phone&quot;: &quot;07595971291&quot;,
        ///  &quot;Mobile&quot;: null,
        ///  &quot;EmailAddress&quot;: &quot;qaayed@hotmail.com&quot;,
        ///  &quot;PaymentMethod&quot;: &quot;BACS&quot;,
        ///  &quot;PayrollRefNumber&quot;: &quot;JLS30499&quot;,
        ///  &quot;StartDate&quot;: &quot;2022-04-01T00:00:00&quot;,
        ///  &quot;EndDate&quot;: null,
        ///  &quot;EmployeeFileId&quot;: &quot;a1025000001sGu5AAE&quot;,
        ///  &quot;Status&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_Candidate_Live {
            get {
                return ResourceManager.GetString("Debug_Candidate_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ClientId&quot;: &quot;0013L00000buT7kQAE&quot;,
        ///  &quot;ClientRef&quot;: &quot;CL-0279112&quot;,
        ///  &quot;ClientName&quot;: &quot;CPE New Client&quot;,
        ///  &quot;IsLegalHirer&quot;: false,
        ///  &quot;NoVat&quot;: false,
        ///  &quot;VatNo&quot;: null,
        ///  &quot;CompanyRegNum&quot;: null,
        ///  &quot;CreditLimit&quot;: null,
        ///  &quot;InvoiceDeliveryMethod&quot;: null,
        ///  &quot;InvoiceEmail&quot;: null,
        ///  &quot;InvoiceEmail2&quot;: null,
        ///  &quot;InvoiceEmail3&quot;: null,
        ///  &quot;EnablePaymentApplications&quot;: null,
        ///  &quot;IsCheckedIn&quot;: true,
        ///  &quot;WorkAddress&quot;: {
        ///    &quot;Street&quot;: &quot;Saint James&apos;s Building, 79 Oxford Street&quot;,
        ///    &quot;City&quot;: &quot;Manchester&quot;,
        ///    &quot;County&quot;: null,
        ///    &quot;Country&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_Client_Live {
            get {
                return ResourceManager.GetString("Debug_Client_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ClientId&quot;: &quot;0013L00000buT7kQAE&quot;,
        ///  &quot;ClientRef&quot;: &quot;CL-0279112&quot;,
        ///  &quot;ClientName&quot;: &quot;CPE New Client&quot;,
        ///  &quot;IsLegalHirer&quot;: false,
        ///  &quot;NoVat&quot;: false,
        ///  &quot;VatNo&quot;: null,
        ///  &quot;CompanyRegNum&quot;: null,
        ///  &quot;CreditLimit&quot;: null,
        ///  &quot;InvoiceDeliveryMethod&quot;: null,
        ///  &quot;InvoiceEmail&quot;: null,
        ///  &quot;InvoiceEmail2&quot;: null,
        ///  &quot;InvoiceEmail3&quot;: null,
        ///  &quot;EnablePaymentApplications&quot;: null,
        ///  &quot;IsCheckedIn&quot;: true,
        ///  &quot;WorkAddress&quot;: {
        ///    &quot;Street&quot;: &quot;Saint James&apos;s Building, 79 Oxford Street&quot;,
        ///    &quot;City&quot;: &quot;Manchester&quot;,
        ///    &quot;County&quot;: n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_ClientContact {
            get {
                return ResourceManager.GetString("Debug_ClientContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Id&quot;: &quot;0054J000002t0xGQAQ&quot;,
        ///  &quot;MigratedUserId&quot;: &quot;PS-10&quot;,
        ///  &quot;EmployeeRef&quot;: &quot;1006&quot;,
        ///  &quot;Firstname&quot;: &quot;Susan&quot;,
        ///  &quot;Lastname&quot;: &quot;Tappers&quot;,
        ///  &quot;Username&quot;: &quot;sue.tapley@ruk-ufo.co.uk.test&quot;,
        ///  &quot;Email&quot;: &quot;susan.tapley@randstad.co.uk&quot;,
        ///  &quot;IsActive&quot;: true,
        ///  &quot;OpCo&quot;: {
        ///    &quot;Id&quot;: &quot;a3R7E0000006mn6UAA&quot;,
        ///    &quot;MigratedGroupId&quot;: null,
        ///    &quot;IsActive&quot;: true,
        ///    &quot;Name&quot;: &quot;Business Solutions&quot;,
        ///    &quot;FinanceCode&quot;: &quot;BS&quot;
        ///  },
        ///  &quot;Unit&quot;: {
        ///    &quot;Id&quot;: &quot;a3R7E0000006mq6UAA&quot;,
        ///    &quot;MigratedGroupId&quot;: &quot;PS-376&quot;,
        ///    &quot;IsActive&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_Consultant {
            get {
                return ResourceManager.GetString("Debug_Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Username&quot;: &quot;jasmin.ahmed@ruk-ufo.co.uk.test&quot;,
        ///  &quot;Profile&quot;: &quot;RUK Standard User&quot;,
        ///  &quot;Name&quot;: &quot;Jasmin Ahmed&quot;,
        ///  &quot;MigratedUserId&quot;: &quot;PS-1019&quot;,
        ///  &quot;LegacyBackofficeId&quot;: &quot;jasmin.ahmed&quot;,
        ///  &quot;Lastname&quot;: &quot;Ahmed&quot;,
        ///  &quot;LastLoginDate&quot;: &quot;2021-05-24T11:43:04.000Z&quot;,
        ///  &quot;IsPortalEnabled&quot;: false,
        ///  &quot;IsActive&quot;: true,
        ///  &quot;Id&quot;: &quot;0054J0000052b0TQAQ&quot;,
        ///  &quot;Firstname&quot;: &quot;Jasmin&quot;,
        ///  &quot;EmployeeRef&quot;: &quot;18266&quot;,
        ///  &quot;Email&quot;: &quot;jasmin.ahmed@randstad.co.uk.invalid&quot;
        ///}.
        /// </summary>
        internal static string Debug_Consultant_Live {
            get {
                return ResourceManager.GetString("Debug_Consultant_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;HolidayRequestId&quot;: &quot;a3G25000000dsGBEAY&quot;,
        ///	&quot;HolidayRequestRef&quot;: &quot;HR-000034329&quot;,
        ///	&quot;Candidate&quot;: {
        ///		&quot;CandidateId&quot;: null,
        ///		&quot;LiveInPayroll&quot;: true,
        ///		&quot;CandidateRef&quot;: &quot;C-001638044&quot;,
        ///		&quot;Title&quot;: null,
        ///		&quot;Name&quot;: null,
        ///		&quot;Surname&quot;: null,
        ///		&quot;Sex&quot;: null,
        ///		&quot;DateOfBirth&quot;: null,
        ///		&quot;NiNumber&quot;: null,
        ///		&quot;Phone&quot;: null,
        ///		&quot;Mobile&quot;: null,
        ///		&quot;EmailAddress&quot;: null,
        ///		&quot;PaymentMethod&quot;: null,
        ///		&quot;PayrollRefNumber&quot;: &quot;CBVA0021&quot;,
        ///		&quot;StartDate&quot;: null,
        ///		&quot;EndDate&quot;: null,
        ///		&quot;EmployeeFileId&quot;: null,
        ///		&quot;Status&quot;: null, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_Holiday_Request_live {
            get {
                return ResourceManager.GetString("Debug_Holiday_Request_live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;SubmittedOn&quot;: &quot;2022-02-04T15:05:38.000Z&quot;,
        ///  &quot;StartDate&quot;: &quot;2022-02-04&quot;,
        ///  &quot;Hours&quot;: 8.00,
        ///  &quot;HolidayRequestRef&quot;: &quot;HR-000013909&quot;,
        ///  &quot;HolidayRequestId&quot;: &quot;a3G8E000000OsWMUA0&quot;,
        ///  &quot;HolidayRequestDate&quot;: &quot;2022-02-04&quot;,
        ///  &quot;EndDate&quot;: &quot;2022-02-05&quot;,
        ///  &quot;Candidate&quot;: {
        ///    &quot;ValidationErrors&quot;: {},
        ///    &quot;Unit&quot;: {
        ///      &quot;Name&quot;: &quot;Unit&quot;,
        ///      &quot;IsBilling&quot;: false,
        ///      &quot;IsActive&quot;: true,
        ///      &quot;Id&quot;: &quot;a3R8E000000EVm2UAG&quot;,
        ///      &quot;FinanceCode&quot;: &quot;B1325&quot;
        ///    },
        ///    &quot;Region&quot;: {
        ///      &quot;Name&quot;: &quot;Region&quot;,
        ///      &quot;IsAc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_HolidayRequest {
            get {
                return ResourceManager.GetString("Debug_HolidayRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;CandidateId&quot;: &quot;a1C7E000003OEhBUAW&quot;,
        ///	&quot;LiveInPayroll&quot;: true,
        ///	&quot;MigratedCandidateId&quot;: null,
        ///	&quot;CandidateRef&quot;: &quot;C-000062336&quot;,
        ///	&quot;Title&quot;: null,
        ///	&quot;Name&quot;: &quot;Test&quot;,
        ///	&quot;Surname&quot;: &quot;Ltd-Worker&quot;,
        ///	&quot;Fullname&quot;: &quot;Test Ltd-Worker&quot;,
        ///	&quot;Salutation&quot;: null,
        ///	&quot;HmrcGender&quot;: &quot;male&quot;,
        ///	&quot;DateOfBirth&quot;: &quot;2000-09-09T00:00:00&quot;,
        ///	&quot;NiNumber&quot;: null,
        ///	&quot;DocumentNumber&quot;: null,
        ///	&quot;MaritalStatus&quot;: null,
        ///	&quot;Nationality&quot;: null,
        ///	&quot;HomeAddress&quot;: {
        ///		&quot;Street&quot;: &quot;Any Street&quot;,
        ///		&quot;City&quot;: &quot;Any Town&quot;,
        ///		&quot;County&quot;: null,
        ///		&quot;Country&quot;: null, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_LtdCandidate {
            get {
                return ResourceManager.GetString("Debug_LtdCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;LastModifiedById&quot;: &quot;0054J000002rDq7QAE&quot;,
        ///  &quot;CreatedById&quot;: &quot;0054J000002rDq7QAE&quot;,
        ///  &quot;UtrNumber&quot;: &quot;123&quot;,
        ///  &quot;SelfBill&quot;: &quot;Yes&quot;,
        ///  &quot;Name&quot;: &quot;Test ltd 2x&quot;,
        ///  &quot;Id&quot;: &quot;a3L8E000001JJPhUAO&quot;,
        ///  &quot;Candidates&quot;: [
        ///    {
        ///      &quot;ValidationErrors&quot;: {},
        ///      &quot;Unit&quot;: {
        ///        &quot;Name&quot;: &quot;Unit 2&quot;,
        ///        &quot;IsBilling&quot;: false,
        ///        &quot;IsActive&quot;: true,
        ///        &quot;Id&quot;: &quot;a3R8E000000EWYjUAO&quot;
        ///      },
        ///      &quot;StartDate&quot;: &quot;2022-02-15&quot;,
        ///      &quot;Region&quot;: {
        ///        &quot;Name&quot;: &quot;Region&quot;,
        ///        &quot;Id&quot;: &quot;a3R8E000000EVm0UAG&quot;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_LtdCompany {
            get {
                return ResourceManager.GetString("Debug_LtdCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;CandidateId&quot;: &quot;a1C7E000003OKkKJJJ&quot;,
        ///	&quot;LiveInPayroll&quot;: true,
        ///	&quot;MigratedCandidateId&quot;: null,
        ///	&quot;CandidateRef&quot;: &quot;C-00005000&quot;,
        ///	&quot;Title&quot;: &quot;Mr&quot;,
        ///	&quot;Name&quot;: &quot;Arnold&quot;,
        ///	&quot;Surname&quot;: &quot;Rimmer&quot;,
        ///	&quot;Fullname&quot;: &quot;Mr Arnold J Rimmer&quot;,
        ///	&quot;Salutation&quot;: null,
        ///	&quot;HmrcGender&quot;: &quot;male&quot;,
        ///	&quot;DateOfBirth&quot;: &quot;1980-05-03T00:00:00&quot;,
        ///	&quot;NiNumber&quot;: &quot;NP123456B&quot;,
        ///	&quot;DocumentNumber&quot;: null,
        ///	&quot;MaritalStatus&quot;: null,
        ///	&quot;Nationality&quot;: &quot;British&quot;,
        ///	&quot;HomeAddress&quot;: {
        ///		&quot;Street&quot;: &quot;66&quot;,
        ///		&quot;City&quot;: &quot;Trinity Rd&quot;,
        ///		&quot;County&quot;: &quot;Bucks&quot;,
        ///		&quot;Countr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_PayeCandidate {
            get {
                return ResourceManager.GetString("Debug_PayeCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Unit&quot;: {
        ///    &quot;Name&quot;: &quot;Unit&quot;,
        ///    &quot;IsBilling&quot;: false,
        ///    &quot;Id&quot;: &quot;a3R8E000000EVm2UAG&quot;,
        ///    &quot;FinanceCode&quot;: &quot;B1325&quot;
        ///  },
        ///  &quot;StartDate&quot;: &quot;2022-01-21&quot;,
        ///  &quot;Salary&quot;: 20000,
        ///  &quot;RsmClient&quot;: {
        ///    &quot;WorkAddress&quot;: {
        ///      &quot;Street&quot;: &quot;68 Trinity Row&quot;,
        ///      &quot;PostCode&quot;: &quot;MK12 5PB&quot;,
        ///      &quot;County&quot;: &quot;Bucks&quot;,
        ///      &quot;Country&quot;: &quot;UK&quot;,
        ///      &quot;City&quot;: &quot;Milton Keynes&quot;
        ///    },
        ///    &quot;OpCo&quot;: {
        ///      &quot;Name&quot;: &quot;Business Solutions&quot;,
        ///      &quot;Id&quot;: &quot;a3R8E000000EVlyUAG&quot;,
        ///      &quot;FinanceCode&quot;: &quot;B1325&quot;
        ///    },
        ///    &quot;CompanyR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_Placement {
            get {
                return ResourceManager.GetString("Debug_Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Unit&quot;: {
        ///    &quot;Id&quot;: &quot;a3R3L000000Cl84UAC&quot;,
        ///    &quot;MigratedGroupId&quot;: null,
        ///    &quot;IsActive&quot;: null,
        ///    &quot;Name&quot;: &quot;Maidstone&quot;,
        ///    &quot;FinanceCode&quot;: &quot;P0022&quot;
        ///  },
        ///  &quot;OpCo&quot;: {
        ///    &quot;Id&quot;: &quot;a3R3L000000Cl40UAC&quot;,
        ///    &quot;MigratedGroupId&quot;: &quot;CPE&quot;,
        ///    &quot;IsActive&quot;: null,
        ///    &quot;Name&quot;: &quot;CPE&quot;,
        ///    &quot;FinanceCode&quot;: &quot;CPE&quot;
        ///  },
        ///  &quot;PlacementRef&quot;: &quot;PL-0068669&quot;,
        ///  &quot;PoNumber&quot;: null,
        ///  &quot;PoRequired&quot;: null,
        ///  &quot;SecondTier&quot;: null,
        ///  &quot;SecondTierFee&quot;: 0.0,
        ///  &quot;StartDate&quot;: &quot;2023-11-01T00:00:00&quot;,
        ///  &quot;PlacementJobTitle&quot;: &quot;paper chil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_Placement_Live {
            get {
                return ResourceManager.GetString("Debug_Placement_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;TimesheetId&quot;: &quot;a1v8d000002uheVAAQ&quot;,
        ///    &quot;AssignmentRef&quot;: &quot;PAs-855644&quot;,
        ///    &quot;AssignmentStart&quot;: &quot;0001-01-01T00:00:00&quot;,
        ///    &quot;Cancelled&quot;: false,
        ///    &quot;PoNumber&quot;: null,
        ///    &quot;TimesheetRef&quot;: &quot;UT06226940&quot;,
        ///    &quot;StartDate&quot;: &quot;2023-11-09&quot;,
        ///    &quot;EndDate&quot;: &quot;2023-11-09&quot;,
        ///    &quot;ExternalTimesheetId&quot;: null,
        ///    &quot;OpCo&quot;: {
        ///        &quot;Id&quot;: &quot;a3R4J000001MuDsUAK&quot;,
        ///        &quot;MigratedGroupId&quot;: null,
        ///        &quot;IsActive&quot;: null,
        ///        &quot;Name&quot;: &quot;Public Services&quot;,
        ///        &quot;FinanceCode&quot;: &quot;PS&quot;
        ///    },
        ///    &quot;Division&quot;: {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_Timesheet_Live {
            get {
                return ResourceManager.GetString("Debug_Timesheet_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;CandidateId&quot;: &quot;a1C7E000003O9zmUAC&quot;,
        ///  &quot;LiveInPayroll&quot;: true,
        ///  &quot;MigratedCandidateId&quot;: null,
        ///  &quot;CandidateRef&quot;: &quot;C-000062242&quot;,
        ///  &quot;Title&quot;: null,
        ///  &quot;Name&quot;: &quot;Sarah&quot;,
        ///  &quot;Surname&quot;: &quot;Stone&quot;,
        ///  &quot;Fullname&quot;: &quot;Sarah Stone&quot;,
        ///  &quot;Salutation&quot;: null,
        ///  &quot;HmrcGender&quot;: &quot;female&quot;,
        ///  &quot;DateOfBirth&quot;: &quot;2000-07-28T00:00:00&quot;,
        ///  &quot;DocumentNumber&quot;: &quot;doc 1234&quot;,
        ///  &quot;MaritalStatus&quot;: null,
        ///  &quot;Nationality&quot;: null,
        ///  &quot;HomeAddress&quot;: {
        ///    &quot;Street&quot;: &quot;3 Cambridge Street&quot;,
        ///    &quot;City&quot;: &quot;Manchester&quot;,
        ///    &quot;County&quot;: null,
        ///    &quot;Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_UmbrellaCandidate {
            get {
                return ResourceManager.GetString("Debug_UmbrellaCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;Code&quot;: &quot;B1021&quot;,
        ///		&quot;Division&quot;: &quot;REB&quot;,
        ///		&quot;InvoiceTemplate&quot;: &quot;&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: &quot;B1022&quot;,
        ///		&quot;Division&quot;: &quot;REB&quot;,
        ///		&quot;InvoiceTemplate&quot;: &quot;&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: &quot;B1042&quot;,
        ///		&quot;Division&quot;: &quot;REB&quot;,
        ///		&quot;InvoiceTemplate&quot;: &quot;&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: &quot;B1043&quot;,
        ///		&quot;Division&quot;: &quot;REB&quot;,
        ///		&quot;InvoiceTemplate&quot;: &quot;&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: &quot;B1044&quot;,
        ///		&quot;Division&quot;: &quot;REB&quot;,
        ///		&quot;InvoiceTemplate&quot;: &quot;&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: &quot;B1046&quot;,
        ///		&quot;Division&quot;: &quot;REB&quot;,
        ///		&quot;InvoiceTemplate&quot;: &quot;&quot;
        ///	},
        ///	{
        ///		&quot;Code&quot;: &quot;B1047&quot;,
        ///		&quot;Division&quot;: &quot;REB&quot;,
        ///		&quot;Invo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DivisionCodes {
            get {
                return ResourceManager.GetString("DivisionCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;CPE&quot;: &quot;RCPE&quot;,
        ///  &quot;PS&quot;: &quot;RC&quot;,
        ///  &quot;BS&quot;: &quot;WEEKLY&quot;, 
        ///  &quot;SWS&quot; : &quot;MONTH&quot;
        ///}.
        /// </summary>
        internal static string EmployerRefs {
            get {
                return ResourceManager.GetString("EmployerRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ClientId&quot;: &quot;0013L00000buT7kQAE&quot;,
        ///  &quot;ClientRef&quot;: &quot;CL-0279112&quot;,
        ///  &quot;ClientName&quot;: &quot;CPE New Client&quot;,
        ///  &quot;IsLegalHirer&quot;: false,
        ///  &quot;NoVat&quot;: false,
        ///  &quot;VatNo&quot;: null,
        ///  &quot;CompanyRegNum&quot;: null,
        ///  &quot;CreditLimit&quot;: null,
        ///  &quot;InvoiceDeliveryMethod&quot;: null,
        ///  &quot;InvoiceEmail&quot;: null,
        ///  &quot;InvoiceEmail2&quot;: null,
        ///  &quot;InvoiceEmail3&quot;: null,
        ///  &quot;EnablePaymentApplications&quot;: null,
        ///  &quot;IsCheckedIn&quot;: true,
        ///  &quot;WorkAddress&quot;: {
        ///    &quot;Street&quot;: &quot;Saint James&apos;s Building, 79 Oxford Street&quot;,
        ///    &quot;City&quot;: &quot;Manchester&quot;,
        ///    &quot;County&quot;: n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HleBillingControlled {
            get {
                return ResourceManager.GetString("HleBillingControlled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ClientId&quot;: &quot;0013L00000ciwQhQAI&quot;,
        ///  &quot;ClientRef&quot;: &quot;CL-0279171&quot;,
        ///  &quot;ClientName&quot;: &quot;Sophie Direct Bill&quot;,
        ///  &quot;IsLegalHirer&quot;: false,
        ///  &quot;NoVat&quot;: false,
        ///  &quot;VatNo&quot;: null,
        ///  &quot;CompanyRegNum&quot;: null,
        ///  &quot;CreditLimit&quot;: 10000.0,
        ///  &quot;InvoiceDeliveryMethod&quot;: null,
        ///  &quot;InvoiceEmail&quot;: null,
        ///  &quot;InvoiceEmail2&quot;: null,
        ///  &quot;InvoiceEmail3&quot;: null,
        ///  &quot;EnablePaymentApplications&quot;: null,
        ///  &quot;IsCheckedIn&quot;: true,
        ///  &quot;WorkAddress&quot;: {
        ///    &quot;Street&quot;: &quot;120 High Street&quot;,
        ///    &quot;City&quot;: &quot;Luton&quot;,
        ///    &quot;County&quot;: null,
        ///    &quot;Country&quot;: nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HleElectronic {
            get {
                return ResourceManager.GetString("HleElectronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ClientId&quot;: &quot;0013L00000buT7kQAE&quot;,
        ///  &quot;ClientRef&quot;: &quot;CL-0279112&quot;,
        ///  &quot;ClientName&quot;: &quot;CPE New Client&quot;,
        ///  &quot;IsLegalHirer&quot;: false,
        ///  &quot;NoVat&quot;: false,
        ///  &quot;VatNo&quot;: null,
        ///  &quot;CompanyRegNum&quot;: null,
        ///  &quot;CreditLimit&quot;: null,
        ///  &quot;InvoiceDeliveryMethod&quot;: null,
        ///  &quot;InvoiceEmail&quot;: null,
        ///  &quot;InvoiceEmail2&quot;: null,
        ///  &quot;InvoiceEmail3&quot;: null,
        ///  &quot;EnablePaymentApplications&quot;: null,
        ///  &quot;IsCheckedIn&quot;: true,
        ///  &quot;WorkAddress&quot;: {
        ///    &quot;Street&quot;: &quot;Saint James&apos;s Building, 79 Oxford Street&quot;,
        ///    &quot;City&quot;: &quot;Manchester&quot;,
        ///    &quot;County&quot;: n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HleSelfBill {
            get {
                return ResourceManager.GetString("HleSelfBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Basic Days&quot;:&quot;P340&quot;,
        ///	&quot;Basic Hours&quot;:&quot;P280&quot;,
        ///	&quot;Basic Hours non NMW&quot;:&quot;P280A&quot;,
        ///	&quot;Accommodation&quot;:&quot;A10&quot;,
        ///	&quot;Back Pay - Non WTR&quot;:&quot;A40&quot;,
        ///	&quot;Back Pay - WTR&quot;:&quot;A30&quot;,
        ///	&quot;Bonus&quot;:&quot;A50&quot;,
        ///	&quot;Congestion Charge&quot;:&quot;A70&quot;,
        ///	&quot;Expenses&quot;:&quot;A80&quot;,
        ///	&quot;Fuel&quot;:&quot;A90&quot;,
        ///	&quot;Meal Allowance&quot;:&quot;A130&quot;,
        ///	&quot;Mileage&quot;:&quot;A140&quot;,
        ///        &quot;Mileage - Lower Rate&quot;:&quot;A140&quot;,
        ///	&quot;Parking&quot;:&quot;A170&quot;,
        ///	&quot;Travel &amp; Subsistence&quot;:&quot;A180&quot;,
        ///	&quot;Afternoon Shift Hours - Non WTR&quot;:&quot;P200&quot;,
        ///	&quot;Back Pay&quot;:&quot;P260&quot;,
        ///	&quot;Bank Holiday&quot;:&quot;P270&quot;,
        ///	&quot;Bank Holiday - Non WTR&quot;:&quot;P1080&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RateMap {
            get {
                return ResourceManager.GetString("RateMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;B1021&quot;: &quot;REB&quot;,
        ///  &quot;B1022&quot;: &quot;REB&quot;,
        ///  &quot;B1042&quot;: &quot;REB&quot;,
        ///  &quot;B1043&quot;: &quot;REB&quot;,
        ///  &quot;B1046&quot;: &quot;REB&quot;,
        ///  &quot;B1047&quot;: &quot;REB&quot;,
        ///  &quot;B1048&quot;: &quot;REB&quot;,
        ///  &quot;B1081&quot;: &quot;REB&quot;,
        ///  &quot;B1084&quot;: &quot;REB&quot;,
        ///  &quot;B1100&quot;: &quot;REB&quot;,
        ///  &quot;B1101&quot;: &quot;REB&quot;,
        ///  &quot;B1102&quot;: &quot;REB&quot;,
        ///  &quot;B1103&quot;: &quot;REB&quot;,
        ///  &quot;B1105&quot;: &quot;REB&quot;,
        ///  &quot;B1106&quot;: &quot;REB&quot;,
        ///  &quot;B1140&quot;: &quot;REB&quot;,
        ///  &quot;B1141&quot;: &quot;REB&quot;,
        ///  &quot;B1200&quot;: &quot;REB&quot;,
        ///  &quot;B1201&quot;: &quot;REB&quot;,
        ///  &quot;B1260&quot;: &quot;REB&quot;,
        ///  &quot;B1261&quot;: &quot;REB&quot;,
        ///  &quot;B1262&quot;: &quot;REB&quot;,
        ///  &quot;B1302&quot;: &quot;REB&quot;,
        ///  &quot;B1305&quot;: &quot;REB&quot;,
        ///  &quot;B1324&quot;: &quot;REB&quot;,
        ///  &quot;B1325&quot;: &quot;REB&quot;,
        ///  &q....
        /// </summary>
        internal static string TomCodes {
            get {
                return ResourceManager.GetString("TomCodes", resourceCulture);
            }
        }
    }
}
