//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Randstad.UfoRsm.BabelFish.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Randstad.UfoRsm.BabelFish.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ClientId&quot;: &quot;0017E00001Hly1ZQAR&quot;,
        ///  &quot;ClientRef&quot;: &quot;CC502321&quot;,
        ///  &quot;MigratedClientId&quot;: null,
        ///  &quot;ClientName&quot;: &quot;Bower Park&quot;,
        ///  &quot;IR35&quot;: true,
        ///  &quot;Status&quot;: &quot;Active&quot;,
        ///  &quot;VatNo&quot;: null,
        ///  &quot;NoVat&quot;: false,
        ///  &quot;PoRequired&quot;: null,
        ///  &quot;InvoiceDeliveryMethod&quot;: null,
        ///  &quot;InvoiceEmail&quot;: null,
        ///  &quot;InvoiceEmail2&quot;: null,
        ///  &quot;InvoiceEmail3&quot;: null,
        ///  &quot;InvoiceAddressNo&quot;: null,
        ///  &quot;HleClient&quot;: null,
        ///  &quot;ParentClient&quot;: null,
        ///  &quot;IsCheckedIn&quot;: true,
        ///  &quot;ActiveInSirenum&quot;: null,
        ///  &quot;Owner&quot;: {
        ///    &quot;Id&quot;: &quot;0054J0000052b0sQAA&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_Client {
            get {
                return ResourceManager.GetString("Debug_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Id&quot;: &quot;0054J000002t0xGQAQ&quot;,
        ///  &quot;MigratedUserId&quot;: &quot;PS-10&quot;,
        ///  &quot;EmployeeRef&quot;: &quot;1006&quot;,
        ///  &quot;Firstname&quot;: &quot;Susan&quot;,
        ///  &quot;Lastname&quot;: &quot;Tappers&quot;,
        ///  &quot;Username&quot;: &quot;sue.tapley@ruk-ufo.co.uk.test&quot;,
        ///  &quot;Email&quot;: &quot;susan.tapley@randstad.co.uk&quot;,
        ///  &quot;IsActive&quot;: true,
        ///  &quot;OpCo&quot;: {
        ///    &quot;Id&quot;: &quot;a3R7E0000006mn6UAA&quot;,
        ///    &quot;MigratedGroupId&quot;: null,
        ///    &quot;IsActive&quot;: true,
        ///    &quot;Name&quot;: &quot;Business Solutions&quot;,
        ///    &quot;FinanceCode&quot;: &quot;BS&quot;
        ///  },
        ///  &quot;Unit&quot;: {
        ///    &quot;Id&quot;: &quot;a3R7E0000006mq6UAA&quot;,
        ///    &quot;MigratedGroupId&quot;: &quot;PS-376&quot;,
        ///    &quot;IsActive&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_Consultant {
            get {
                return ResourceManager.GetString("Debug_Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;CandidateId&quot;: &quot;a1C7E000003OEhBUAW&quot;,
        ///	&quot;LiveInPayroll&quot;: true,
        ///	&quot;MigratedCandidateId&quot;: null,
        ///	&quot;CandidateRef&quot;: &quot;C-000062336&quot;,
        ///	&quot;Title&quot;: null,
        ///	&quot;Name&quot;: &quot;Test&quot;,
        ///	&quot;Surname&quot;: &quot;Ltd-Worker&quot;,
        ///	&quot;Fullname&quot;: &quot;Test Ltd-Worker&quot;,
        ///	&quot;Salutation&quot;: null,
        ///	&quot;Gender&quot;: &quot;male&quot;,
        ///	&quot;DateOfBirth&quot;: &quot;2000-09-09T00:00:00&quot;,
        ///	&quot;NiNumber&quot;: null,
        ///	&quot;DocumentNumber&quot;: null,
        ///	&quot;MaritalStatus&quot;: null,
        ///	&quot;Nationality&quot;: null,
        ///	&quot;HomeAddress&quot;: {
        ///		&quot;Street&quot;: &quot;Any Street&quot;,
        ///		&quot;City&quot;: &quot;Any Town&quot;,
        ///		&quot;County&quot;: null,
        ///		&quot;Country&quot;: null,
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_LtdCandidate {
            get {
                return ResourceManager.GetString("Debug_LtdCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;CandidateId&quot;: &quot;a1C7E000003OKkKUAW&quot;,
        ///	&quot;LiveInPayroll&quot;: true,
        ///	&quot;MigratedCandidateId&quot;: null,
        ///	&quot;CandidateRef&quot;: &quot;C-000064041&quot;,
        ///	&quot;Title&quot;: &quot;Mr&quot;,
        ///	&quot;Name&quot;: &quot;Bailie&quot;,
        ///	&quot;Surname&quot;: &quot;Rhys Titchner&quot;,
        ///	&quot;Fullname&quot;: &quot;Bailie Rhys Titchner&quot;,
        ///	&quot;Salutation&quot;: null,
        ///	&quot;Gender&quot;: &quot;male&quot;,
        ///	&quot;DateOfBirth&quot;: &quot;1980-05-03T00:00:00&quot;,
        ///	&quot;NiNumber&quot;: &quot;NP123456A&quot;,
        ///	&quot;DocumentNumber&quot;: null,
        ///	&quot;MaritalStatus&quot;: null,
        ///	&quot;Nationality&quot;: &quot;British&quot;,
        ///	&quot;HomeAddress&quot;: {
        ///		&quot;Street&quot;: &quot;1000&quot;,
        ///		&quot;City&quot;: &quot;Capability Green&quot;,
        ///		&quot;County&quot;: null, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_PayeCandidate {
            get {
                return ResourceManager.GetString("Debug_PayeCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;CandidateId&quot;: &quot;a1C7E000003O9zmUAC&quot;,
        ///  &quot;LiveInPayroll&quot;: true,
        ///  &quot;MigratedCandidateId&quot;: null,
        ///  &quot;CandidateRef&quot;: &quot;C-000062242&quot;,
        ///  &quot;Title&quot;: null,
        ///  &quot;Name&quot;: &quot;Sarah&quot;,
        ///  &quot;Surname&quot;: &quot;Stone&quot;,
        ///  &quot;Fullname&quot;: &quot;Sarah Stone&quot;,
        ///  &quot;Salutation&quot;: null,
        ///  &quot;Gender&quot;: &quot;female&quot;,
        ///  &quot;DateOfBirth&quot;: &quot;2000-07-28T00:00:00&quot;,
        ///  &quot;NiNumber&quot;: &quot;SL094311A&quot;,
        ///  &quot;DocumentNumber&quot;: null,
        ///  &quot;MaritalStatus&quot;: null,
        ///  &quot;Nationality&quot;: null,
        ///  &quot;HomeAddress&quot;: {
        ///    &quot;Street&quot;: &quot;3 Cambridge Street&quot;,
        ///    &quot;City&quot;: &quot;Manchester&quot;,
        ///    &quot;Count [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Debug_UmbrellaCandidate {
            get {
                return ResourceManager.GetString("Debug_UmbrellaCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;CPE&quot;: &quot;RCPE&quot;,
        ///  &quot;PS&quot;: &quot;RC&quot;,
        ///  &quot;BS&quot;: &quot;WEEKLY&quot; 
        ///}.
        /// </summary>
        internal static string EmployerRefs {
            get {
                return ResourceManager.GetString("EmployerRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Basic Days&quot;:&quot;P340&quot;,
        ///	&quot;Basic Hours&quot;:&quot;P280&quot;,
        ///	&quot;Accommodation&quot;:&quot;A10&quot;,
        ///	&quot;Back Pay - Non WTR&quot;:&quot;A40&quot;,
        ///	&quot;Back Pay - WTR&quot;:&quot;A30&quot;,
        ///	&quot;Bonus&quot;:&quot;A50&quot;,
        ///	&quot;Congestion Charge&quot;:&quot;A70&quot;,
        ///	&quot;Expenses&quot;:&quot;A80&quot;,
        ///	&quot;Fuel&quot;:&quot;A90&quot;,
        ///	&quot;Meal Allowance&quot;:&quot;A130&quot;,
        ///	&quot;Mileage&quot;:&quot;A140&quot;,
        ///	&quot;Parking&quot;:&quot;A170&quot;,
        ///	&quot;Travel &amp; Subsistence&quot;:&quot;A180&quot;,
        ///	&quot;Afternoon Shift Hours - Non WTR&quot;:&quot;P200&quot;,
        ///	&quot;Back Pay&quot;:&quot;P260&quot;,
        ///	&quot;Bank Holiday&quot;:&quot;P270&quot;,
        ///	&quot;Bank Holiday - Non WTR&quot;:&quot;P1080&quot;,
        ///	&quot;Bank Holiday Day&quot;:&quot;P210&quot;,
        ///	&quot;Bank Holiday Hours&quot;:&quot;P230&quot;,
        ///	&quot;Bank Holida [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RateMap {
            get {
                return ResourceManager.GetString("RateMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;B1021&quot;: &quot;REB&quot;,
        ///  &quot;B1022&quot;: &quot;REB&quot;,
        ///  &quot;B1042&quot;: &quot;REB&quot;,
        ///  &quot;B1043&quot;: &quot;REB&quot;,
        ///  &quot;B1046&quot;: &quot;REB&quot;,
        ///  &quot;B1047&quot;: &quot;REB&quot;,
        ///  &quot;B1048&quot;: &quot;REB&quot;,
        ///  &quot;B1081&quot;: &quot;REB&quot;,
        ///  &quot;B1084&quot;: &quot;REB&quot;,
        ///  &quot;B1100&quot;: &quot;REB&quot;,
        ///  &quot;B1101&quot;: &quot;REB&quot;,
        ///  &quot;B1102&quot;: &quot;REB&quot;,
        ///  &quot;B1103&quot;: &quot;REB&quot;,
        ///  &quot;B1105&quot;: &quot;REB&quot;,
        ///  &quot;B1106&quot;: &quot;REB&quot;,
        ///  &quot;B1140&quot;: &quot;REB&quot;,
        ///  &quot;B1141&quot;: &quot;REB&quot;,
        ///  &quot;B1200&quot;: &quot;REB&quot;,
        ///  &quot;B1201&quot;: &quot;REB&quot;,
        ///  &quot;B1260&quot;: &quot;REB&quot;,
        ///  &quot;B1261&quot;: &quot;REB&quot;,
        ///  &quot;B1262&quot;: &quot;REB&quot;,
        ///  &quot;B1302&quot;: &quot;REB&quot;,
        ///  &quot;B1305&quot;: &quot;REB&quot;,
        ///  &quot;B1324&quot;: &quot;REB&quot;,
        ///  &quot;B1325&quot;: &quot;REB&quot;,
        ///  &q....
        /// </summary>
        internal static string TomCodes {
            get {
                return ResourceManager.GetString("TomCodes", resourceCulture);
            }
        }
    }
}
